from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

#downloaded from https://gist.github.com/rogerallen/1583593
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    'District Of Columbia': 'DC',
    'Georgia (State)':'GA'
}

#create udf to return state abbreviation
state_udf=udf(lambda x: us_state_abbrev[x],StringType())

abbrev_state = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
}
abbrev_state_udf=udf(lambda x: abbrev_state[x],StringType())

city_codes= {'ALC'	:	'ALCAN             ',
              'ANC'	:	'ANCHORAGE         ',
              'BAR'	:	'BAKER AAF - BAKER ISLAND',
              'DAC'	:	'DALTONS CACHE     ',
              'PIZ'	:	'DEW STATION PT LAY DEW',
              'DTH'	:	'DUTCH HARBOR      ',
              'EGL'	:	'EAGLE             ',
              'FRB'	:	'FAIRBANKS         ',
              'HOM'	:	'HOMER             ',
              'HYD'	:	'HYDER             ',
              'JUN'	:	'JUNEAU            ',
              '5KE'	:	'KETCHIKAN',
              'KET'	:	'KETCHIKAN         ',
              'MOS'	:	'MOSES POINT INTERMEDIATE',
              'NIK'	:	'NIKISKI           ',
              'NOM'	:	'NOM               ',
              'PKC'	:	'POKER CREEK       ',
              'ORI'	:	'PORT LIONS SPB',
              'SKA'	:	'SKAGWAY           ',
              'SNP'	:	'ST. PAUL ISLAND',
              'TKI'	:	'TOKEEN',
              'WRA'	:	'WRANGELL          ',
              'HSV'	:	'HUNTSVILLE',
              'MOB'	:	'MOBILE            ',
              'LIA'	:	'LITTLE ROCK',
              'ROG'	:	'ROGERS ARPT',
              'DOU'	:	'DOUGLAS           ',
              'LUK'	:	'LUKEVILLE         ',
              'MAP'	:	'MARIPOSA            ',
              'NAC'	:	'NACO              ',
              'NOG'	:	'NOGALES           ',
              'PHO'	:	'PHOENIX           ',
              'POR'	:	'PORTAL',
              'SLU'	:	'SAN LUIS          ',
              'SAS'	:	'SASABE            ',
              'TUC'	:	'TUCSON            ',
              'YUI'	:	'YUMA              ',
              'AND'	:	'ANDRADE           ',
              'BUR'	:	'BURBANK',
              'CAL'	:	'CALEXICO          ',
              'CAO'	:	'CAMPO             ',
              'FRE'	:	'FRESNO            ',
              'ICP'	:	'IMPERIAL COUNTY   ',
              'LNB'	:	'LONG BEACH         ',
              'LOS'	:	'LOS ANGELES       ',
              'BFL'	:	'BAKERSFIELD',
              'OAK'	:	'OAKLAND ',
              'ONT'	:	'ONTARIO',
              'OTM'	:	'OTAY MESA          ',
              'BLT'	:	'PACIFIC, HWY. STATION ',
              'PSP'	:	'PALM SPRINGS',
              'SAC'	:	'SACRAMENTO        ',
              'SLS'	:	'SALINAS (BPS)',
              'SDP'	:	'SAN DIEGO',
              'SFR'	:	'SAN FRANCISCO     ',
              'SNJ'	:	'SAN JOSE          ',
              'SLO'	:	'SAN LUIS OBISPO   ',
              'SLI'	:	'SAN LUIS OBISPO (BPS)',
              'SPC'	:	'SAN PEDRO         ',
              'SYS'	:	'SAN YSIDRO        ',
              'SAA'	:	'SANTA ANA         ',
              'STO'	:	'STOCKTON (BPS)',
              'TEC'	:	'TECATE            ',
              'TRV'	:	'TRAVIS-AFB        ',
              'APA'	:	'ARAPAHOE COUNTY',
              'ASE'	:	'ASPEN #ARPT',
              'COS'	:	'COLORADO SPRINGS',
              'DEN'	:	'DENVER            ',
              'DRO'	:	'LA PLATA - DURANGO',
              'BDL'	:	'BRADLEY INTERNATIONAL',
              'BGC'	:	'BRIDGEPORT        ',
              'GRT'	:	'GROTON            ',
              'HAR'	:	'HARTFORD          ',
              'NWH'	:	'NEW HAVEN         ',
              'NWL'	:	'NEW LONDON        ',
              'TST'	:	'NEWINGTON DATA CENTER TEST',
              'WAS'	:	'WASHINGTON DC         ',
              'DOV'	:	'DOVER AFB',
              'DVD'	:	'DOVER-AFB         ',
              'WLL'	:	'WILMINGTON        ',
              'BOC'	:	'BOCAGRANDE        ',
              'SRQ'	:	'BRADENTON - SARASOTA',
              'CAN'	:	'CAPE CANAVERAL    ',
              'DAB'	:	'DAYTONA BEACH INTERNATIONAL',
              'FRN'	:	'FERNANDINA        ',
              'FTL'	:	'FORT LAUDERDALE   ',
              'FMY'	:	'FORT MYERS        ',
              'FPF'	:	'FORT PIERCE       ',
              'HUR'	:	'HURLBURT FIELD',
              'GNV'	:	'J R ALISON MUNI - GAINESVILLE',
              'JAC'	:	'JACKSONVILLE      ',
              'KEY'	:	'KEY WEST          ',
              'LEE'	:	'LEESBURG MUNICIPAL AIRPORT',
              'MLB'	:	'MELBOURNE',
              'MIA'	:	'MIAMI             ',
              'APF'	:	'NAPLES #ARPT',
              'OPF'	:	'OPA LOCKA',
              'ORL'	:	'ORLANDO           ',
              'PAN'	:	'PANAMA CITY       ',
              'PEN'	:	'PENSACOLA         ',
              'PCF'	:	'PORT CANAVERAL    ',
              'PEV'	:	'PORT EVERGLADES   ',
              'PSJ'	:	'PORT ST JOE       ',
              'SFB'	:	'SANFORD           ',
              'SGJ'	:	'ST AUGUSTINE ARPT',
              'SAU'	:	'ST AUGUSTINE      ',
              'FPR'	:	'ST LUCIE COUNTY',
              'SPE'	:	'ST PETERSBURG     ',
              'TAM'	:	'TAMPA             ',
              'WPB'	:	'WEST PALM BEACH   ',
              'ATL'	:	'ATLANTA           ',
              'BRU'	:	'BRUNSWICK         ',
              'AGS'	:	'BUSH FIELD - AUGUSTA',
              'SAV'	:	'SAVANNAH          ',
              'AGA'	:	'AGANA             ',
              'HHW'	:	'HONOLULU          ',
              'OGG'	:	'KAHULUI - MAUI',
              'KOA'	:	'KEAHOLE-KONA      ',
              'LIH'	:	'LIHUE             ',
              'CID'	:	'CEDAR RAPIDS/IOWA CITY',
              'DSM'	:	'DES MOINES',
              'BOI'	:	'AIR TERM. (GOWEN FLD) BOISE',
              'EPI'	:	'EASTPORT          ',
              'IDA'	:	'FANNING FIELD - IDAHO FALLS',
              'PTL'	:	'PORTHILL          ',
              'SPI'	:	'CAPITAL - SPRINGFIELD',
              'CHI'	:	'CHICAGO           ',
              'DPA'	:	'DUPAGE COUNTY',
              'PIA'	:	'GREATER PEORIA',
              'RFD'	:	'GREATER ROCKFORD',
              'UGN'	:	'MEMORIAL - WAUKEGAN',
              'GAR'	:	'GARY              ',
              'HMM'	:	'HAMMOND           ',
              'INP'	:	'INDIANAPOLIS      ',
              'MRL'	:	'MERRILLVILLE      ',
              'SBN'	:	'SOUTH BEND',
              'ICT'	:	'MID-CONTINENT - WITCHITA',
              'LEX'	:	'BLUE GRASS - LEXINGTON',
              'LOU'	:	'LOUISVILLE        ',
              'BTN'	:	'BATON ROUGE       ',
              'LKC'	:	'LAKE CHARLES      ',
              'LAK'	:	'LAKE CHARLES (BPS)',
              'MLU'	:	'MONROE',
              'MGC'	:	'MORGAN CITY       ',
              'NOL'	:	'NEW ORLEANS       ',
              'BOS'	:	'BOSTON            ',
              'GLO'	:	'GLOUCESTER        ',
              'BED'	:	'HANSCOM FIELD - BEDFORD',
              'LYN'	:	'LYNDEN            ',
              'ADW'	:	'ANDREWS AFB',
              'BAL'	:	'BALTIMORE         ',
              'MKG'	:	'MUSKEGON',
              'PAX'	:	'PATUXENT RIVER    ',
              'BGM'	:	'BANGOR            ',
              'BOO'	:	'BOOTHBAY HARBOR   ',
              'BWM'	:	'BRIDGEWATER       ',
              'BCK'	:	'BUCKPORT          ',
              'CLS'	:	'CALAIS   ',
              'CRB'	:	'CARIBOU           ',
              'COB'	:	'COBURN GORE       ',
              'EST'	:	'EASTCOURT         ',
              'EPT'	:	'EASTPORT MUNICIPAL',
              'EPM'	:	'EASTPORT          ',
              'FOR'	:	'FOREST CITY       ',
              'FTF'	:	'FORT FAIRFIELD    ',
              'FTK'	:	'FORT KENT         ',
              'HML'	:	'HAMIIN            ',
              'HTM'	:	'HOULTON           ',
              'JKM'	:	'JACKMAN           ',
              'KAL'	:	'KALISPEL          ',
              'LIM'	:	'LIMESTONE         ',
              'LUB'	:	'LUBEC             ',
              'MAD'	:	'MADAWASKA         ',
              'POM'	:	'PORTLAND          ',
              'RGM'	:	'RANGELEY (BPS)',
              'SBR'	:	'SOUTH BREWER      ',
              'SRL'	:	'ST AURELIE        ',
              'SPA'	:	'ST PAMPILE        ',
              'VNB'	:	'VAN BUREN         ',
              'VCB'	:	'VANCEBORO         ',
              'AGN'	:	'ALGONAC           ',
              'ALP'	:	'ALPENA            ',
              'BCY'	:	'BAY CITY          ',
              'DET'	:	'DETROIT           ',
              'GRP'	:	'GRAND RAPIDS',
              'GRO'	:	'GROSSE ISLE       ',
              'ISL'	:	'ISLE ROYALE       ',
              'MRC'	:	'MARINE CITY       ',
              'MRY'	:	'MARYSVILLE        ',
              'PTK'	:	'OAKLAND COUNTY - PONTIAC',
              'PHU'	:	'PORT HURON        ',
              'RBT'	:	'ROBERTS LANDING   ',
              'SAG'	:	'SAGINAW           ',
              'SSM'	:	'SAULT STE. MARIE  ',
              'SCL'	:	'ST CLAIR          ',
              'YIP'	:	'WILLOW RUN - YPSILANTI',
              'BAU'	:	'BAUDETTE          ',
              'CAR'	:	'CARIBOU MUNICIPAL AIRPORT',
              'GTF'	:	'Collapsed into INT',
              'INL'	:	'Collapsed into INT',
              'CRA'	:	'CRANE LAKE        ',
              'MIC'	:	'CRYSTAL MUNICIPAL AIRPORT',
              'DUL'	:	'DULUTH            ',
              'ELY'	:	'ELY               ',
              'GPM'	:	'GRAND PORTAGE     ',
              'SVC'	:	'GRANT COUNTY - SILVER CITY',
              'INT'	:	'INT''L FALLS      ',
              'LAN'	:	'LANCASTER         ',
              'MSP'	:	'MINN./ST PAUL     ',
              'LIN'	:	'NORTHERN SVC CENTER   ',
              'NOY'	:	'NOYES             ',
              'PIN'	:	'PINE CREEK        ',
              '48Y'	:	'PINECREEK BORDER ARPT',
              'RAN'	:	'RAINER            ',
              'RST'	:	'ROCHESTER',
              'ROS'	:	'ROSEAU            ',
              'SPM'	:	'ST PAUL           ',
              'WSB'	:	'WARROAD INTL',
              'WAR'	:	'WARROAD           ',
              'KAN'	:	'KANSAS CITY       ',
              'SGF'	:	'SPRINGFIELD-BRANSON',
              'STL'	:	'ST LOUIS          ',
              'WHI'	:	'WHITETAIL         ',
              'WHM'	:	'WILD HORSE        ',
              'GPT'	:	'BILOXI REGIONAL',
              'GTR'	:	'GOLDEN TRIANGLE LOWNDES CNTY',
              'GUL'	:	'GULFPORT          ',
              'PAS'	:	'PASCAGOULA        ',
              'JAN'	:	'THOMPSON FIELD - JACKSON',
              'BIL'	:	'BILLINGS          ',
              'BTM'	:	'BUTTE             ',
              'CHF'	:	'CHIEF MT          ',
              'CTB'	:	'CUT BANK MUNICIPAL',
              'CUT'	:	'CUT BANK          ',
              'DLB'	:	'DEL BONITA        ',
              'EUR'	:	'EUREKA (BPS)',
              'BZN'	:	'GALLATIN FIELD - BOZEMAN',
              'FCA'	:	'GLACIER NATIONAL PARK',
              'GGW'	:	'GLASGOW           ',
              'GRE'	:	'GREAT FALLS       ',
              'HVR'	:	'HAVRE             ',
              'HEL'	:	'HELENA            ',
              'LWT'	:	'LEWISTON          ',
              'MGM'	:	'MORGAN            ',
              'OPH'	:	'OPHEIM            ',
              'PIE'	:	'PIEGAN            ',
              'RAY'	:	'RAYMOND           ',
              'ROO'	:	'ROOSVILLE         ',
              'SCO'	:	'SCOBEY            ',
              'SWE'	:	'SWEETGTASS        ',
              'TRL'	:	'TRIAL CREEK       ',
              'TUR'	:	'TURNER            ',
              'WCM'	:	'WILLOW CREEK      ',
              'CLT'	:	'CHARLOTTE         ',
              'FAY'	:	'FAYETTEVILLE',
              'MRH'	:	'MOREHEAD CITY     ',
              'FOP'	:	'MORRIS FIELDS AAF',
              'GSO'	:	'PIEDMONT TRIAD INTL AIRPORT',
              'RDU'	:	'RALEIGH/DURHAM    ',
              'SSC'	:	'SHAW AFB - SUMTER',
              'WIL'	:	'WILMINGTON        ',
              'AMB'	:	'AMBROSE           ',
              'ANT'	:	'ANTLER            ',
              'CRY'	:	'CARBURY           ',
              'DNS'	:	'DUNSEITH          ',
              'FAR'	:	'FARGO             ',
              'FRT'	:	'FORTUNA           ',
              'GRF'	:	'GRAND FORKS       ',
              'HNN'	:	'HANNAH            ',
              'HNS'	:	'HANSBORO          ',
              'MAI'	:	'MAIDA             ',
              'MND'	:	'MINOT             ',
              'NEC'	:	'NECHE             ',
              'NOO'	:	'NOONAN            ',
              'NRG'	:	'NORTHGATE         ',
              'PEM'	:	'PEMBINA           ',
              'SAR'	:	'SARLES            ',
              'SHR'	:	'SHERWOOD          ',
              'SJO'	:	'ST JOHN           ',
              'WAL'	:	'WALHALLA          ',
              'WHO'	:	'WESTHOPE          ',
              'WND'	:	'WILLISTON         ',
              'OMA'	:	'OMAHA             ',
              'LEB'	:	'LEBANON           ',
              'MHT'	:	'MANCHESTER',
              'PNH'	:	'PITTSBURG         ',
              'PSM'	:	'PORTSMOUTH        ',
              'BYO'	:	'BAYONNE           ',
              'CNJ'	:	'CAMDEN            ',
              'HOB'	:	'HOBOKEN           ',
              'JER'	:	'JERSEY CITY       ',
              'WRI'	:	'MC GUIRE AFB - WRIGHTSOWN',
              'MMU'	:	'MORRISTOWN',
              'NEW'	:	'NEWARK/TETERBORO  ',
              'PER'	:	'PERTH AMBOY       ',
              'ACY'	:	'POMONA FIELD - ATLANTIC CITY',
              'ALA'	:	'ALAMAGORDO (BPS)',
              'ABQ'	:	'ALBUQUERQUE       ',
              'ANP'	:	'ANTELOPE WELLS    ',
              'CRL'	:	'CARLSBAD          ',
              'COL'	:	'COLUMBUS          ',
              'CDD'	:	'CRANE LAKE - ST. LOUIS CNTY',
              'DNM'	:	'DEMING (BPS)',
              'LAS'	:	'LAS CRUCES        ',
              'LOB'	:	'LORDSBURG (BPS)',
              'RUI'	:	'RUIDOSO',
              'STR'	:	'SANTA TERESA      ',
              'RNO'	:	'CANNON INTL - RENO/TAHOE',
              'FLX'	:	'FALLON MUNICIPAL AIRPORT',
              'LVG'	:	'LAS VEGAS         ',
              'REN'	:	'RENO              ',
              'ALB'	:	'ALBANY            ',
              'AXB'	:	'ALEXANDRIA BAY    ',
              'BUF'	:	'BUFFALO           ',
              'CNH'	:	'CANNON CORNERS',
              'CAP'	:	'CAPE VINCENT      ',
              'CHM'	:	'CHAMPLAIN         ',
              'CHT'	:	'CHATEAUGAY        ',
              'CLA'	:	'CLAYTON           ',
              'FTC'	:	'FORT COVINGTON    ',
              'LAG'	:	'LA GUARDIA        ',
              'LEW'	:	'LEWISTON          ',
              'MAS'	:	'MASSENA           ',
              'MAG'	:	'MCGUIRE AFB       ',
              'MOO'	:	'MOORES            ',
              'MRR'	:	'MORRISTOWN        ',
              'NYC'	:	'NEW YORK          ',
              'NIA'	:	'NIAGARA FALLS     ',
              'OGD'	:	'OGDENSBURG        ',
              'OSW'	:	'OSWEGO            ',
              'ELM'	:	'REGIONAL ARPT - HORSEHEAD',
              'ROC'	:	'ROCHESTER         ',
              'ROU'	:	'ROUSES POINT      ',
              'SWF'	:	'STEWART - ORANGE CNTY',
              'SYR'	:	'SYRACUSE          ',
              'THO'	:	'THOUSAND ISLAND BRIDGE',
              'TRO'	:	'TROUT RIVER       ',
              'WAT'	:	'WATERTOWN         ',
              'HPN'	:	'WESTCHESTER - WHITE PLAINS',
              'WRB'	:	'WHIRLPOOL BRIDGE',
              'YOU'	:	'YOUNGSTOWN        ',
              'AKR'	:	'AKRON             ',
              'ATB'	:	'ASHTABULA         ',
              'CIN'	:	'CINCINNATI        ',
              'CLE'	:	'CLEVELAND         ',
              'CLM'	:	'COLUMBUS          ',
              'LOR'	:	'LORAIN            ',
              'MBO'	:	'MARBLE HEADS      ',
              'SDY'	:	'SANDUSKY          ',
              'TOL'	:	'TOLEDO            ',
              'OKC'	:	'OKLAHOMA CITY     ',
              'TUL'	:	'TULSA',
              'AST'	:	'ASTORIA           ',
              'COO'	:	'COOS BAY          ',
              'HIO'	:	'HILLSBORO',
              'MED'	:	'MEDFORD           ',
              'NPT'	:	'NEWPORT           ',
              'POO'	:	'PORTLAND          ',
              'PUT'	:	'PUT-IN-BAY        ',
              'RDM'	:	'ROBERTS FIELDS - REDMOND',
              'ERI'	:	'ERIE              ',
              'MDT'	:	'HARRISBURG',
              'HSB'	:	'HARRISONBURG      ',
              'PHI'	:	'PHILADELPHIA      ',
              'PIT'	:	'PITTSBURG         ',
              'AGU'	:	'AGUADILLA         ',
              'BQN'	:	'BORINQUEN - AGUADILLO',
              'JCP'	:	'CULEBRA - BENJAMIN RIVERA',
              'ENS'	:	'ENSENADA          ',
              'FAJ'	:	'FAJARDO           ',
              'HUM'	:	'HUMACAO           ',
              'JOB'	:	'JOBOS             ',
              'MAY'	:	'MAYAGUEZ          ',
              'PON'	:	'PONCE             ',
              'PSE'	:	'PONCE-MERCEDITA',
              'SAJ'	:	'SAN JUAN          ',
              'VQS'	:	'VIEQUES-ARPT',
              'PRO'	:	'PROVIDENCE        ',
              'PVD'	:	'THEODORE FRANCIS - WARWICK',
              'CHL'	:	'CHARLESTON        ',
              'CAE'	:	'COLUMBIA #ARPT',
              'GEO'	:	'GEORGETOWN        ',
              'GSP'	:	'GREENVILLE',
              'GRR'	:	'GREER',
              'MYR'	:	'MYRTLE BEACH',
              'SPF'	:	'BLACK HILLS, SPEARFISH',
              'HON'	:	'HOWES REGIONAL ARPT - HURON',
              'SAI'	:	'SAIPAN, SPN           ',
              'TYS'	:	'MC GHEE TYSON - ALCOA',
              'MEM'	:	'MEMPHIS           ',
              'NSV'	:	'NASHVILLE         ',
              'TRI'	:	'TRI CITY ARPT',
              'ADS'	:	'ADDISON AIRPORT- ADDISON',
              'ADT'	:	'AMISTAD DAM       ',
              'ANZ'	:	'ANZALDUAS',
              'AUS'	:	'AUSTIN            ',
              'BEA'	:	'BEAUMONT          ',
              'BBP'	:	'BIG BEND PARK (BPS)',
              'SCC'	:	'BP SPEC COORD. CTR',
              'BTC'	:	'BP TACTICAL UNIT  ',
              'BOA'	:	'BRIDGE OF AMERICAS',
              'BRO'	:	'BROWNSVILLE       ',
              'CRP'	:	'CORPUS CHRISTI    ',
              'DAL'	:	'DALLAS            ',
              'DLR'	:	'DEL RIO           ',
              'DNA'	:	'DONNA',
              'EGP'	:	'EAGLE PASS        ',
              'ELP'	:	'EL PASO           ',
              'FAB'	:	'FABENS            ',
              'FAL'	:	'FALCON HEIGHTS    ',
              'FTH'	:	'FORT HANCOCK      ',
              'AFW'	:	'FORT WORTH ALLIANCE',
              'FPT'	:	'FREEPORT          ',
              'GAL'	:	'GALVESTON         ',
              'HLG'	:	'HARLINGEN         ',
              'HID'	:	'HIDALGO           ',
              'HOU'	:	'HOUSTON           ',
              'SGR'	:	'HULL FIELD, SUGAR LAND ARPT',
              'LLB'	:	'JUAREZ-LINCOLN BRIDGE',
              'LCB'	:	'LAREDO COLUMBIA BRIDGE',
              'LRN'	:	'LAREDO NORTH      ',
              'LAR'	:	'LAREDO            ',
              'LSE'	:	'LOS EBANOS        ',
              'IND'	:	'LOS INDIOS',
              'LOI'	:	'LOS INDIOS        ',
              'MRS'	:	'MARFA (BPS)',
              'MCA'	:	'MCALLEN           ',
              'MAF'	:	'ODESSA REGIONAL',
              'PDN'	:	'PASO DEL NORTE,TX     ',
              'PBB'	:	'PEACE BRIDGE      ',
              'PHR'	:	'PHARR             ',
              'PAR'	:	'PORT ARTHUR       ',
              'ISB'	:	'PORT ISABEL       ',
              'POE'	:	'PORT OF EL PASO   ',
              'PRE'	:	'PRESIDIO          ',
              'PGR'	:	'PROGRESO          ',
              'RIO'	:	'RIO GRANDE CITY   ',
              'ROM'	:	'ROMA              ',
              'SNA'	:	'SAN ANTONIO       ',
              'SNN'	:	'SANDERSON         ',
              'VIB'	:	'VETERAN INTL BRIDGE',
              'YSL'	:	'YSLETA            ',
              'CHA'	:	'CHARLOTTE AMALIE  ',
              'CHR'	:	'CHRISTIANSTED     ',
              'CRU'	:	'CRUZ BAY, ST JOHN ',
              'FRK'	:	'FREDERIKSTED      ',
              'STT'	:	'ST THOMAS         ',
              'LGU'	:	'CACHE AIRPORT - LOGAN',
              'SLC'	:	'SALT LAKE CITY    ',
              'CHO'	:	'ALBEMARLE CHARLOTTESVILLE',
              'DAA'	:	'DAVISON AAF - FAIRFAX CNTY',
              'HOP'	:	'HOPEWELL          ',
              'HEF'	:	'MANASSAS #ARPT',
              'NWN'	:	'NEWPORT           ',
              'NOR'	:	'NORFOLK           ',
              'RCM'	:	'RICHMOND          ',
              'ABS'	:	'ALBURG SPRINGS    ',
              'ABG'	:	'ALBURG            ',
              'BEB'	:	'BEEBE PLAIN       ',
              'BEE'	:	'BEECHER FALLS     ',
              'BRG'	:	'BURLINGTON        ',
              'CNA'	:	'CANAAN            ',
              'DER'	:	'DERBY LINE (I-91) ',
              'DLV'	:	'DERBY LINE (RT. 5)',
              'ERC'	:	'EAST RICHFORD     ',
              'HIG'	:	'HIGHGATE SPRINGS  ',
              'MOR'	:	'MORSES LINE       ',
              'NPV'	:	'NEWPORT           ',
              'NRT'	:	'NORTH TROY        ',
              'NRN'	:	'NORTON            ',
              'PIV'	:	'PINNACLE ROAD     ',
              'RIF'	:	'RICHFORT          ',
              'STA'	:	'ST ALBANS         ',
              'SWB'	:	'SWANTON (BP - SECTOR HQ)',
              'WBE'	:	'WEST BERKSHIRE    ',
              'ABE'	:	'ABERDEEN          ',
              'ANA'	:	'ANACORTES         ',
              'BEL'	:	'BELLINGHAM        ',
              'BLI'	:	'BELLINGHAMSHINGTON #INTL',
              'BLA'	:	'BLAINE            ',
              'BWA'	:	'BOUNDARY          ',
              'CUR'	:	'CURLEW (BPS)',
              'DVL'	:	'DANVILLE          ',
              'EVE'	:	'EVERETT           ',
              'FER'	:	'FERRY             ',
              'FRI'	:	'FRIDAY HARBOR     ',
              'FWA'	:	'FRONTIER          ',
              'KLM'	:	'KALAMA            ',
              'LAU'	:	'LAURIER           ',
              'LON'	:	'LONGVIEW          ',
              'MET'	:	'METALINE FALLS    ',
              'MWH'	:	'MOSES LAKE GRANT COUNTY ARPT',
              'NEA'	:	'NEAH BAY          ',
              'NIG'	:	'NIGHTHAWK         ',
              'OLY'	:	'OLYMPIA           ',
              'ORO'	:	'OROVILLE          ',
              'PWB'	:	'PASCO             ',
              'PIR'	:	'POINT ROBERTS     ',
              'PNG'	:	'PORT ANGELES      ',
              'PTO'	:	'PORT TOWNSEND     ',
              'SEA'	:	'SEATTLE           ',
              'SPO'	:	'SPOKANE           ',
              'SUM'	:	'SUMAS             ',
              'TAC'	:	'TACOMA            ',
              'PSC'	:	'TRI-CITIES - PASCO',
              'VAN'	:	'VANCOUVER         ',
              'AGM'	:	'ALGOMA            ',
              'BAY'	:	'BAYFIELD          ',
              'GRB'	:	'GREEN BAY         ',
              'MNW'	:	'MANITOWOC         ',
              'MIL'	:	'MILWAUKEE         ',
              'MSN'	:	'TRUAX FIELD - DANE COUNTY',
              'CHS'	:	'CHARLESTON        ',
              'CLK'	:	'CLARKSBURG        ',
              'BLF'	:	'MERCER COUNTY',
              'CSP'	:	'CASPER            ',
              'XXX': 'NOT REPORTED/UNKNOWN  ',
              '888': 'UNIDENTIFED AIR / SEAPORT',
              'UNK': 'UNKNOWN POE           ',
              'CLG': 'CALGARY, CANADA       ',
              'EDA': 'EDMONTON, CANADA      ',
              'YHC': 'HAKAI PASS, CANADA',
              'HAL': 'Halifax, NS, Canada   ',
              'MON': 'MONTREAL, CANADA      ',
              'OTT': 'OTTAWA, CANADA        ',
              'YXE': 'SASKATOON, CANADA',
              'TOR': 'TORONTO, CANADA       ',
              'VCV': 'VANCOUVER, CANADA     ',
              'VIC': 'VICTORIA, CANADA      ',
              'WIN': 'WINNIPEG, CANADA      ',
              'AMS': 'AMSTERDAM-SCHIPHOL, NETHERLANDS',
              'ARB': 'ARUBA, NETH ANTILLES  ',
              'BAN': 'BANKOK, THAILAND      ',
              'BEI': 'BEICA #ARPT, ETHIOPIA',
              'PEK': 'BEIJING CAPITAL INTL, PRC',
              'BDA': 'KINDLEY FIELD, BERMUDA',
              'BOG': 'BOGOTA, EL DORADO #ARPT, COLOMBIA',
              'EZE': 'BUENOS AIRES, MINISTRO PIST, ARGENTINA',
              'CUN': 'CANCUN, MEXICO',
              'CRQ': 'CARAVELAS, BA #ARPT, BRAZIL',
              'MVD': 'CARRASCO, URUGUAY',
              'DUB': 'DUBLIN, IRELAND       ',
              'FOU': 'FOUGAMOU #ARPT, GABON',
              'FBA': 'FREEPORT, BAHAMAS      ',
              'MTY': 'GEN M. ESCOBEDO, Monterrey, MX',
              'HMO': 'GEN PESQUEIRA GARCIA, MX',
              'GCM': 'GRAND CAYMAN, CAYMAN ISLAND',
              'GDL': 'GUADALAJARA, MIGUEL HIDAL, MX',
              'HAM': 'HAMILTON, BERMUDA     ',
              'ICN': 'INCHON, SEOUL KOREA',
              'IWA': 'INVALID - IWAKUNI, JAPAN',
              'CND': 'KOGALNICEANU, ROMANIA',
              'LAH': 'LABUHA ARPT, INDONESIA',
              'DUR': 'LOUIS BOTHA, SOUTH AFRICA',
              'MAL': 'MANGOLE ARPT, INDONESIA',
              'MDE': 'MEDELLIN, COLOMBIA',
              'MEX': 'JUAREZ INTL, MEXICO CITY, MX',
              'LHR': 'MIDDLESEX, ENGLAND',
              'NBO': 'NAIROBI, KENYA        ',
              'NAS': 'NASSAU, BAHAMAS       ',
              'NCA': 'NORTH CAICOS, TURK & CAIMAN',
              'PTY': 'OMAR TORRIJOS, PANAMA',
              'SPV': 'PAPUA, NEW GUINEA',
              'UIO': 'QUITO (MARISCAL SUCR), ECUADOR',
              'RIT': 'ROME, ITALY           ',
              'SNO': 'SAKON NAKHON #ARPT, THAILAND',
              'SLP': 'SAN LUIS POTOSI #ARPT, MEXICO',
              'SAN': 'SAN SALVADOR, EL SALVADOR',
              'SRO': 'SANTANA RAMOS #ARPT, COLOMBIA',
              'GRU': 'GUARULHOS INTL, SAO PAULO, BRAZIL',
              'SHA': 'SHANNON, IRELAND      ',
              'HIL': 'SHILLAVO, ETHIOPIA',
              'TOK': 'TOROKINA #ARPT, PAPUA, NEW GUINEA',
              'VER': 'VERACRUZ, MEXICO',
              'LGW': 'WEST SUSSEX, ENGLAND  ',
              'ZZZ': 'MEXICO Land (Banco de Mexico) ',
              'CHN': 'No PORT Code (CHN)',
              'CNC': 'CANNON CORNERS, NY',
              'MAA': 'Abu Dhabi',
              'AG0': 'MAGNOLIA',
              'BHM': 'BAR HARBOR',
              'BHX': 'BIRMINGHAM',
              'CAK': 'AKRON',
              'FOK': 'SUFFOLK COUNTY',
              'LND': 'LANDER',
              'MAR': 'MARFA',
              'MLI': 'MOLINE',
              'RIV': 'RIVERSIDE',
              'RME': 'ROME',
              'VNY': 'VAN NUYS',
              'YUM': 'YUMA',
             'W55': 'SEATTLE'
              }

city_code_udf=udf(lambda x:city_codes[x],StringType())